// Postgres schema, embedded so the serverless bundle needs no file reads.
export default String.raw`
SET client_min_messages = warning; -- no "already exists, skipping" notices on every boot
-- Caisse Panne Hôtel — hotel maintenance & breakdown logbook database schema.
--
-- Design notes:
--  * The whole breakdown lifecycle lives on the 'pannes' row: it starts as an
--    open ticket, is assigned to a technician or contractor, moves through
--    diagnosis / waiting for parts / repair / testing, and ends resolved then
--    closed. Its 'status' is the single source of truth for where a ticket is
--    — the same role 'reservations.status' plays in Caisse Rent.
--  * A room's 'status' is never set directly by the UI; it is moved by the
--    panne lifecycle services (create / resolve / close) so the hotel view
--    can't disagree with the maintenance view.
--  * Every state change runs in one SQL transaction (see server/db.ts) and
--    is written to 'audit_logs'.

-- Postgres (Supabase) dialect. Timestamps stay TEXT in the same
-- 'YYYY-MM-DD HH:MM:SS' UTC shape the SQLite version used, so the UI's date
-- formatting and the string comparisons in reports are unchanged.
-- Idempotent: runs on every server cold start.

CREATE OR REPLACE FUNCTION now_txt() RETURNS TEXT LANGUAGE sql STABLE AS
  $$ SELECT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS') $$;
CREATE OR REPLACE FUNCTION now_txt(shift INTERVAL) RETURNS TEXT LANGUAGE sql STABLE AS
  $$ SELECT to_char((now() + shift) AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS') $$;
CREATE OR REPLACE FUNCTION today_txt() RETURNS TEXT LANGUAGE sql STABLE AS
  $$ SELECT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD') $$;
CREATE OR REPLACE FUNCTION today_txt(shift INTERVAL) RETURNS TEXT LANGUAGE sql STABLE AS
  $$ SELECT to_char((now() + shift) AT TIME ZONE 'UTC', 'YYYY-MM-DD') $$;
-- Hours between two stored timestamps (accepts both the SQL-default and JS ISO shapes).
CREATE OR REPLACE FUNCTION hours_between(a TEXT, b TEXT) RETURNS DOUBLE PRECISION LANGUAGE sql IMMUTABLE AS
  $$ SELECT EXTRACT(EPOCH FROM (replace(replace(b,'T',' '),'Z','')::timestamp - replace(replace(a,'T',' '),'Z','')::timestamp)) / 3600.0 $$;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  full_name TEXT NOT NULL,
  role TEXT NOT NULL CHECK(role IN ('admin','manager','reception','housekeeping','technician','it')),
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT (now_txt())
);

CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

CREATE TABLE IF NOT EXISTS buildings (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS rooms (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  building_id INTEGER REFERENCES buildings(id),
  floor TEXT,
  room_number TEXT NOT NULL,
  room_type TEXT,
  status TEXT NOT NULL DEFAULT 'available' CHECK(status IN ('available','occupied','maintenance','out_of_service')),
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT (now_txt()),
  UNIQUE(building_id, room_number)
);
CREATE INDEX IF NOT EXISTS idx_rooms_building ON rooms(building_id);
CREATE INDEX IF NOT EXISTS idx_rooms_status ON rooms(status);

CREATE TABLE IF NOT EXISTS areas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  building_id INTEGER REFERENCES buildings(id),
  name TEXT NOT NULL,
  area_type TEXT NOT NULL DEFAULT 'other',
  notes TEXT
);
CREATE INDEX IF NOT EXISTS idx_areas_building ON areas(building_id);

CREATE TABLE IF NOT EXISTS equipment (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'other',
  room_id INTEGER REFERENCES rooms(id),
  area_id INTEGER REFERENCES areas(id),
  building_id INTEGER REFERENCES buildings(id),
  brand TEXT,
  model TEXT,
  serial_number TEXT,
  install_date TEXT,
  warranty_expiry TEXT,
  status TEXT NOT NULL DEFAULT 'operational' CHECK(status IN ('operational','needs_repair','out_of_service')),
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT (now_txt()),
  updated_at TEXT NOT NULL DEFAULT (now_txt())
);
CREATE INDEX IF NOT EXISTS idx_equipment_room ON equipment(room_id);
CREATE INDEX IF NOT EXISTS idx_equipment_area ON equipment(area_id);
CREATE INDEX IF NOT EXISTS idx_equipment_status ON equipment(status);

CREATE TABLE IF NOT EXISTS contractors (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company TEXT NOT NULL,
  contact_name TEXT,
  phone TEXT,
  email TEXT,
  service_type TEXT,
  contract_info TEXT,
  rate DOUBLE PRECISION,
  notes TEXT,
  active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS suppliers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  contact_name TEXT,
  phone TEXT,
  email TEXT,
  notes TEXT,
  active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS inventory_parts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'other',
  unit TEXT NOT NULL DEFAULT 'pièce',
  quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
  min_quantity DOUBLE PRECISION NOT NULL DEFAULT 0,
  unit_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
  supplier_id INTEGER REFERENCES suppliers(id),
  location TEXT,
  part_number TEXT,
  notes TEXT
);
CREATE INDEX IF NOT EXISTS idx_parts_category ON inventory_parts(category);

CREATE TABLE IF NOT EXISTS purchase_orders (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po_number TEXT NOT NULL UNIQUE,
  supplier_id INTEGER REFERENCES suppliers(id),
  status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','ordered','received','cancelled')),
  created_by INTEGER REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT (now_txt()),
  received_at TEXT,
  notes TEXT
);
CREATE INDEX IF NOT EXISTS idx_po_status ON purchase_orders(status);

CREATE TABLE IF NOT EXISTS purchase_order_lines (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  po_id INTEGER NOT NULL REFERENCES purchase_orders(id),
  part_id INTEGER REFERENCES inventory_parts(id),
  label TEXT NOT NULL,
  qty DOUBLE PRECISION NOT NULL DEFAULT 1,
  unit_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_po_lines_po ON purchase_order_lines(po_id);

CREATE TABLE IF NOT EXISTS pannes (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_number TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL DEFAULT 'other'
    CHECK(category IN ('electrical','ac','plumbing','heating','room_equipment','building','housekeeping','network','computer','telephony','tv_system','other')),
  priority TEXT NOT NULL DEFAULT 'medium' CHECK(priority IN ('critical','high','medium','low')),
  guest_impact TEXT NOT NULL DEFAULT 'none' CHECK(guest_impact IN ('none','minor','significant','room_unusable','hotel_wide')),
  location_type TEXT NOT NULL DEFAULT 'room' CHECK(location_type IN ('room','area','building')),
  room_id INTEGER REFERENCES rooms(id),
  area_id INTEGER REFERENCES areas(id),
  building_id INTEGER REFERENCES buildings(id),
  equipment_id INTEGER REFERENCES equipment(id),
  reported_by_user_id INTEGER REFERENCES users(id),
  reported_by_role TEXT,
  department TEXT NOT NULL DEFAULT 'maintenance' CHECK(department IN ('maintenance','it')),
  status TEXT NOT NULL DEFAULT 'open'
    CHECK(status IN ('open','assigned','diagnosis','waiting_parts','in_repair','testing','need_info','escalated','resolved','closed','cancelled')),
  assigned_to INTEGER REFERENCES users(id),
  contractor_id INTEGER REFERENCES contractors(id),
  diagnosis TEXT,
  cause TEXT,
  recommended_action TEXT,
  parts_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
  labor_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
  contractor_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
  total_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT (now_txt()),
  assigned_at TEXT,
  resolved_at TEXT,
  closed_at TEXT,
  updated_at TEXT NOT NULL DEFAULT (now_txt())
);
-- Upgrades for databases created before departments (IT team) and the
-- need_info / escalated statuses. Each CHECK is only rebuilt when it is still
-- the old one, so a normal boot does no ALTER at all.
ALTER TABLE pannes ADD COLUMN IF NOT EXISTS department TEXT NOT NULL DEFAULT 'maintenance' CHECK(department IN ('maintenance','it'));
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'users_role_check' AND pg_get_constraintdef(oid) LIKE '%''it''%') THEN
    ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
    ALTER TABLE users ADD CONSTRAINT users_role_check CHECK(role IN ('admin','manager','reception','housekeeping','technician','it'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pannes_status_check' AND pg_get_constraintdef(oid) LIKE '%need_info%') THEN
    ALTER TABLE pannes DROP CONSTRAINT IF EXISTS pannes_status_check;
    ALTER TABLE pannes ADD CONSTRAINT pannes_status_check
      CHECK(status IN ('open','assigned','diagnosis','waiting_parts','in_repair','testing','need_info','escalated','resolved','closed','cancelled'));
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pannes_category_check' AND pg_get_constraintdef(oid) LIKE '%network%') THEN
    ALTER TABLE pannes DROP CONSTRAINT IF EXISTS pannes_category_check;
    ALTER TABLE pannes ADD CONSTRAINT pannes_category_check
      CHECK(category IN ('electrical','ac','plumbing','heating','room_equipment','building','housekeeping','network','computer','telephony','tv_system','other'));
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_pannes_status ON pannes(status);
CREATE INDEX IF NOT EXISTS idx_pannes_department ON pannes(department);
CREATE INDEX IF NOT EXISTS idx_pannes_priority ON pannes(priority);
CREATE INDEX IF NOT EXISTS idx_pannes_category ON pannes(category);
CREATE INDEX IF NOT EXISTS idx_pannes_room ON pannes(room_id);
CREATE INDEX IF NOT EXISTS idx_pannes_equipment ON pannes(equipment_id);
CREATE INDEX IF NOT EXISTS idx_pannes_assigned ON pannes(assigned_to);
CREATE INDEX IF NOT EXISTS idx_pannes_created ON pannes(created_at);

CREATE TABLE IF NOT EXISTS panne_interventions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  panne_id INTEGER NOT NULL REFERENCES pannes(id),
  technician_id INTEGER REFERENCES users(id),
  description TEXT,
  started_at TEXT,
  finished_at TEXT,
  result TEXT,
  created_at TEXT NOT NULL DEFAULT (now_txt())
);
CREATE INDEX IF NOT EXISTS idx_interventions_panne ON panne_interventions(panne_id);

-- The ticket's conversation: comments, and status changes with their note.
CREATE TABLE IF NOT EXISTS panne_comments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  panne_id INTEGER NOT NULL REFERENCES pannes(id),
  user_id INTEGER REFERENCES users(id),
  body TEXT,
  status TEXT,
  created_at TEXT NOT NULL DEFAULT (now_txt())
);
CREATE INDEX IF NOT EXISTS idx_panne_comments_panne ON panne_comments(panne_id);

CREATE TABLE IF NOT EXISTS panne_parts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  panne_id INTEGER NOT NULL REFERENCES pannes(id),
  part_id INTEGER REFERENCES inventory_parts(id),
  label TEXT NOT NULL,
  qty DOUBLE PRECISION NOT NULL DEFAULT 1,
  unit_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
  amount DOUBLE PRECISION NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (now_txt())
);
CREATE INDEX IF NOT EXISTS idx_panne_parts_panne ON panne_parts(panne_id);

CREATE TABLE IF NOT EXISTS panne_photos (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  panne_id INTEGER NOT NULL REFERENCES pannes(id),
  file_path TEXT NOT NULL,
  caption TEXT,
  stage TEXT NOT NULL DEFAULT 'other' CHECK(stage IN ('before','during','after','other')),
  created_at TEXT NOT NULL DEFAULT (now_txt())
);
CREATE INDEX IF NOT EXISTS idx_panne_photos_panne ON panne_photos(panne_id);

CREATE TABLE IF NOT EXISTS inventory_movements (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  part_id INTEGER NOT NULL REFERENCES inventory_parts(id),
  type TEXT NOT NULL CHECK(type IN ('in','out','adjust')),
  qty DOUBLE PRECISION NOT NULL,
  reason TEXT,
  panne_id INTEGER REFERENCES pannes(id),
  purchase_order_id INTEGER REFERENCES purchase_orders(id),
  user_id INTEGER REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT (now_txt())
);
CREATE INDEX IF NOT EXISTS idx_movements_part ON inventory_movements(part_id);
CREATE INDEX IF NOT EXISTS idx_movements_created ON inventory_movements(created_at);

CREATE TABLE IF NOT EXISTS maintenance_schedules (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  equipment_id INTEGER REFERENCES equipment(id),
  area_id INTEGER REFERENCES areas(id),
  building_id INTEGER REFERENCES buildings(id),
  frequency_type TEXT NOT NULL DEFAULT 'months' CHECK(frequency_type IN ('days','weeks','months')),
  frequency_value INTEGER NOT NULL DEFAULT 1,
  checklist TEXT,
  assigned_to INTEGER REFERENCES users(id),
  last_completed_at TEXT,
  next_due_date TEXT NOT NULL DEFAULT (today_txt()),
  active INTEGER NOT NULL DEFAULT 1,
  notes TEXT,
  created_at TEXT NOT NULL DEFAULT (now_txt())
);
CREATE INDEX IF NOT EXISTS idx_schedules_due ON maintenance_schedules(next_due_date);
CREATE INDEX IF NOT EXISTS idx_schedules_active ON maintenance_schedules(active);

CREATE TABLE IF NOT EXISTS maintenance_completions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  schedule_id INTEGER NOT NULL REFERENCES maintenance_schedules(id),
  completed_at TEXT NOT NULL DEFAULT (now_txt()),
  user_id INTEGER REFERENCES users(id),
  checklist_results TEXT,
  notes TEXT,
  cost DOUBLE PRECISION NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_completions_schedule ON maintenance_completions(schedule_id);

CREATE TABLE IF NOT EXISTS shift_handovers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shift TEXT NOT NULL DEFAULT 'day' CHECK(shift IN ('morning','afternoon','night','day')),
  notes TEXT NOT NULL,
  created_by INTEGER REFERENCES users(id),
  created_at TEXT NOT NULL DEFAULT (now_txt())
);
CREATE INDEX IF NOT EXISTS idx_handovers_created ON shift_handovers(created_at);

CREATE TABLE IF NOT EXISTS audit_logs (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  action TEXT NOT NULL,
  entity_type TEXT,
  entity_id INTEGER,
  details TEXT,
  created_at TEXT NOT NULL DEFAULT (now_txt())
);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON audit_logs(created_at);
CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs(action);

-- The app talks to Postgres only through its own server (as the table
-- owner, which bypasses RLS). Enabling RLS with no policies makes Supabase's
-- public Data API return nothing for these tables.
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE buildings ENABLE ROW LEVEL SECURITY;
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE equipment ENABLE ROW LEVEL SECURITY;
ALTER TABLE contractors ENABLE ROW LEVEL SECURITY;
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_parts ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_order_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE pannes ENABLE ROW LEVEL SECURITY;
ALTER TABLE panne_interventions ENABLE ROW LEVEL SECURITY;
ALTER TABLE panne_parts ENABLE ROW LEVEL SECURITY;
ALTER TABLE panne_photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE panne_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE maintenance_completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE shift_handovers ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;

-- Live refresh: one counter bumped by any write to a data table. Screens poll
-- it (sync:version) and reload only when it moved. audit_logs is left out so
-- a login alone doesn't make every screen reload.
CREATE TABLE IF NOT EXISTS app_state (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  version BIGINT NOT NULL DEFAULT 0
);
INSERT INTO app_state (id, version) VALUES (1, 0) ON CONFLICT (id) DO NOTHING;
ALTER TABLE app_state ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION bump_app_version() RETURNS trigger LANGUAGE plpgsql AS
  $$ BEGIN UPDATE app_state SET version = version + 1 WHERE id = 1; RETURN NULL; END $$;

DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['users','settings','buildings','rooms','areas','equipment','contractors','suppliers',
    'inventory_parts','purchase_orders','purchase_order_lines','pannes','panne_interventions','panne_parts',
    'panne_photos','panne_comments','inventory_movements','maintenance_schedules','maintenance_completions','shift_handovers']
  LOOP
    EXECUTE format('CREATE OR REPLACE TRIGGER bump_app_version AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON %I FOR EACH STATEMENT EXECUTE FUNCTION bump_app_version()', t);
  END LOOP;
END $$;
`;
